name: Build Module
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build Module
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: pwsh
      run: ./build.ps1 -Task Build -Bootstrap
